services:
  client_bdd:
    image: mysql:9.4.0
    env_file:
      - .env
    volumes:
      - mysql-client-data:/var/lib/mysql
      - ./bdd/client:/docker-entrypoint-initdb.d
    networks:
      - app-network
    container_name: client_bdd
  
  commande_bdd:
    image: mysql:9.4.0
    env_file:
      - .env
    volumes:
      - mysql-order-data:/var/lib/mysql
      - ./bdd/commande:/docker-entrypoint-initdb.d
    networks:
      - app-network
    container_name: commande_bdd

  api_client:
    build:
      context: ./api_client
    env_file:
      - api_client/.env
    ports:
      - 8080:8000
    depends_on:
      - client_bdd
    networks:
      - app-network
  
  api_commande:
    build:
      context: ./api_commande
    env_file:
      - api_commande/.env
    ports:
      - 8081:8000
    depends_on:
      - commande_bdd
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge

volumes:
  mysql-client-data:
  mysql-order-data: